[versions]
compose = "1.3.1"
android-gradle-plugin = "8.1.0"
kotlin = "1.9.0"

[plugins]
android.application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin.android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin.compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-activity-compose = "androidx.activity:activity-compose:1.6.1"
androidx-compose-ui = "androidx.compose.ui:ui:1.3.1"
androidx-compose-material = "androidx.compose.material:material:1.3.1"
androidx-material3 = "androidx.compose.material3:material3:1.0.0"
